### ISSUE TITLE
Modelica.Fluid.Interfaces.FluidPort_a

### ISSUE THREAD

**Issue by XiongbaXu** [ibpsa/modelica-ibpsa#1789] opened 2023-09-13 02:45 UTC
I developed a Modelica model, I want to link this model to other models, so I used the port, but I encounter a question, when I want to get the value of port.C_outflow, I always meet problems:[Cannot resolve type of expression 1 - port_in.C_outflow. The operands have types Integer, Real[0] in component <NO_COMPONENT>.](omeditmessagesbrowser:///testdac_4?lineNumber=117). 

![image](https://github.com/ibpsa/modelica-ibpsa/assets/140901145/f833b674-6db9-42c0-972e-2bd0701136ba)
![image](https://github.com/ibpsa/modelica-ibpsa/assets/140901145/771dc361-d568-4f5f-9a57-124fac3e0d51)

**Comment by hcasperfu** [comment] 2023-09-13 15:24
Greetings!
Upon a quick look at your screenshot, the translation error may have come from using the placeholder medium model `Modelica.Media.Interfaces.Partialmedium` which is "incomplete" (as intended). It should help if you directly declare it as `Buildings.Media.Air` (as you commented out in line 10). However, I cannot tell if this setup is intended and the placeholder will be replaced in a higher-level model. It would be great if you could provide more code or attach the .mo file so we can look at it closer.
Also, this looks like a generic inquiry rather than an IBPSA issue. I invite you to post questions on [Buildings library's discussion board](https://github.com/lbl-srg/modelica-buildings/discussions).
Closing the issue.

**Closed by hcasperfu** 2023-09-13 15:24 UTC

**Comment by XiongbaXu** [comment] 2023-09-13 15:42
> Greetings! Upon a quick look at your screenshot, the translation error may have come from using the placeholder medium model `Modelica.Media.Interfaces.Partialmedium` which is "incomplete" (as intended). It should help if you directly declare it as `Buildings.Media.Air` (as you commented out in line 10). However, I cannot tell if this setup is intended and the placeholder will be replaced in a higher-level model. It would be great if you could provide more code or attach the .mo file so we can look at it closer. Also, this looks like a generic inquiry rather than an IBPSA issue. I invite you to post questions on [Buildings library's discussion board](https://github.com/lbl-srg/modelica-buildings/discussions). Closing the issue.

Thank you a lot for your reply. I have tried the method that you provided, but the problem is not solved. I also post this question on the discussion board. Thank you.
