### ISSUE TITLE
Signal overwrite/send block that does not require a socket connection

### ISSUE THREAD

**Issue by dhblum** [ibpsa/modelica-ibpsa#1059] opened 2018-12-17 14:57 UTC
This issue is to add signal overwrite and send blocks that do not require a socket connection, as described in https://github.com/ibpsa/project1-boptest/issues/15.  This is an alternative solution implementation to https://github.com/ibpsa/modelica-ibpsa/issues/926.

**Comment by dhblum** [comment] 2019-01-29 15:41
The private parameter names should be changed to boptestOverwrite and boptestRead.

**Comment by mwetter** [comment] 2019-03-27 16:45
@dhblum Should the overwrite block be merged to the master or is it not yet stable?

**Comment by dhblum** [comment] 2019-03-29 20:46
@mwetter The block is not yet stable.  To do:
- [ ] Add enumeration parameter for KPI keywords
- [ ] Add string parameter for variable description

**Comment by JavierArroyoBastida** [comment] 2019-04-11 17:05
@dhblum and @mwetter, 
The enumeration of the KPI signals has been merged in https://github.com/ibpsa/modelica-ibpsa/pull/1116. So far we are using entries for power and energy because we wanted the emulator developer to decide where to integrate: in the model or in the KPI calculator in python. However, I find that misleading and prone to errors in the tagging and the KPI calculation processes. 
For instance the computation of cost and emissions requires power signals since prices and emission factors can vary over time whereas with an energy signal the information of when the energy was consumed is lost.
What do you think? should I leave the energy signals out and compute everything from powers?

**Comment by dhblum** [comment] 2019-07-05 20:07
@mwetter I've added documentation and reference results for this branch, though the unittests still seem to be failing on travis and I can't figure out why.  Can you please take a look at let me know what seems to be the issue?

See https://travis-ci.org/ibpsa/modelica-ibpsa/jobs/554825134

**Comment by mwetter** [comment] 2019-07-08 15:08
@dhblum 
the problem is that `package.order` is incorrect:
```
# Check for package.order to be up to date
(cd  ../../../../IBPSA; \
	  python -c 'import buildingspy.development.refactor as r; \
	  r.write_package_order(".", recursive=True)'; \
	  git diff --exit-code . )
diff --git a/IBPSA/Utilities/IO/SignalExchange/Examples/BaseClasses/package.order b/IBPSA/Utilities/IO/SignalExchange/Examples/BaseClasses/package.order
index 380159e..48dc8ed 100644
--- a/IBPSA/Utilities/IO/SignalExchange/Examples/BaseClasses/package.order
+++ b/IBPSA/Utilities/IO/SignalExchange/Examples/BaseClasses/package.order
@@ -1,2 +1,2 @@
-OriginalModel
 ExportedModel
+OriginalModel
diff --git a/IBPSA/Utilities/IO/SignalExchange/package.order b/IBPSA/Utilities/IO/SignalExchange/package.order
index 46a2d61..8b93087 100644
--- a/IBPSA/Utilities/IO/SignalExchange/package.order
+++ b/IBPSA/Utilities/IO/SignalExchange/package.order
@@ -1,4 +1,4 @@
 Overwrite
 Read
-Examples
 SignalTypes
+Examples
make: *** [test-autogenerated-files] Error 1
```
You can fix it by running locally
```
cd  ../../../../IBPSA; \
	  python -c 'import buildingspy.development.refactor as r; \
	  r.write_package_order(".", recursive=True)'; 
```
and commit the updated files.

**Comment by dhblum** [comment] 2019-07-11 13:59
Thanks @mwetter this worked.

**Closed** 2019-08-13 08:06 UTC
