### ISSUE TITLE
Incorrectly tagged impure functions in geothermal package

### ISSUE THREAD

**Issue by MassimoCimmino** [ibpsa/modelica-ibpsa#1582] opened 2022-02-04 18:25 UTC
`IBPSA.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.internalResistancesOneUTube` and `IBPSA.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.internalResistancesTwoUTube` have had the impure keyword introduced in #1564.

I am not sure these functions require the `impure` keyword. Their outputs are predictable, and do not rely on read/write operations on external files. They may have been mixed in with `IBPSA.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.LoadAggregation.temperatureResponseMatrix` due to the use of a variable named `sha`.

The contexts are different, in the first case `sha` is the shank spacing and in the second `sha` is the SHA-1 encryption of g-function arguments used to read/write a file on disk.

**Comment by mwetter** [comment] 2022-02-08 13:54
@MassimoCimmino : Do you need the impure declaration? The problem is that the function uses `print`, which is not pure. Adding the `pure()` statement around print is not allowed. Dymola fails with
```
Check of [IBPSA.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.Examples.BoreholeTwoUTube](modelica://IBPSA.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.Examples.BoreholeTwoUTube):

Resolve error: Inside a function it is not legal to use the function: pure
```
So, we could leave the function as is and close this issue, or remove the print statement and the `printDebug` flag in `partialInternalResistances`.

**Comment by mwetter** [comment] 2022-02-08 22:44
It would be great if you can remove the print statements if you have no
need for them.

**Closed** 2022-03-04 12:35 UTC
