### ISSUE TITLE
Odd temperature behaviour inside stratified storage

### ISSUE THREAD

**Issue by EnginUcar** [ibpsa/modelica-ibpsa#1157] opened 2019-06-11 15:10 UTC
While working with the ``IBPSA.Fluid.Storage.Stratified`` model, an odd behaviour regarding the temperature inside the tank occurred. The input to the tank is a massflow with prescribed cosine function. Normally we'd expect a periodic behaviour but after simulating the results of the temperature of the tanks heatPort seem strange:

![StorageTestSingle](https://user-images.githubusercontent.com/51709365/59283939-b1917500-8c6b-11e9-8d8a-ee7f9180f521.png)

This only occurrs with a start temperature ```T_start=284.15``` inside the tank.

This is the code to reproduce the issue:

```modelica
model StorageTestSingle "Example for the storage node"
  extends Modelica.Icons.Example;

   package Medium = IBPSA.Media.Specialized.Water.ConstantProperties_pT (
    T_nominal=273.15+10,
    p_nominal=600000.0,
    T_default=273.15+10);
  IBPSA.Fluid.Storage.Stratified tan(
    redeclare package Medium = Medium,
    m_flow_nominal=10,
    VTan=200,
    hTan=10,
    dIns=0.03,
    nSeg=5,
    T_start=284.15) "Storage tank for ectogrid"
    annotation (Placement(transformation(extent={{20,-10},{40,10}})));
  IBPSA.Fluid.Sources.MassFlowSource_T Segment1(
    redeclare package Medium = Medium,
    use_m_flow_in=true,
    m_flow=3,
    T=289.15,
    nPorts=1) "Fluid reservoir at cold side"
    annotation (Placement(transformation(extent={{-48,-10},{-28,10}})));
  IBPSA.Fluid.Sensors.TemperatureTwoPort senT_supply(
    redeclare package Medium = Medium,
    m_flow_nominal=1,
    tau=0) "Supply flow temperature sensor"
    annotation (Placement(transformation(extent={{-10,-10},{10,10}})));
  IBPSA.Fluid.Sources.Boundary_pT sink(redeclare package Medium = Medium,
      nPorts=1) "Fluid reservoir at hot line" annotation (Placement(
        transformation(
        extent={{-10,-10},{10,10}},
        rotation=180,
        origin={70,0})));
  Modelica.Blocks.Sources.Cosine cosine(
    amplitude=2.5,
    freqHz=1/1e7,
    offset=1) annotation (Placement(transformation(extent={{-92,-2},{-72,18}})));
equation 
  connect(Segment1.ports[1], senT_supply.port_a)
    annotation (Line(points={{-28,0},{-10,0}}, color={0,127,255}));
  connect(senT_supply.port_b, tan.port_a)
    annotation (Line(points={{10,0},{20,0}}, color={0,127,255}));
  connect(sink.ports[1], tan.port_b)
    annotation (Line(points={{60,0},{40,0}}, color={0,127,255}));
  connect(cosine.y, Segment1.m_flow_in)
    annotation (Line(points={{-71,8},{-50,8}}, color={0,0,127}));

  annotation (experiment(StopTime=41500000, Interval=3600));
end StorageTestSingle;
```

I also wanted to reproduce this issue with two identical storages but with different start temperatures each (```T_start=283.15``` and ```T_start=285.15```). These are the results for the temperature inside the tanks:

![StorageTestDouble](https://user-images.githubusercontent.com/51709365/59282676-96256a80-8c69-11e9-8aaa-f094b6292c3f.png)

This is the code to reproduce the issue:

```modelica
model StorageTestDouble
  extends Modelica.Icons.Example;

package Medium = IBPSA.Media.Specialized.Water.ConstantProperties_pT (
  T_nominal=273.15+10,
  p_nominal=600000.0,
  T_default=273.15+10);

  IBPSA.Fluid.Storage.Stratified tan2(
    redeclare package Medium = Medium,
    m_flow_nominal=10,
    VTan=200,
    hTan=10,
    dIns=0.03,
    nSeg=5,
    T_start=283.15) "Storage tank for ectogrid"
    annotation (Placement(transformation(extent={{0,-48},{20,-28}})));
  IBPSA.Fluid.Sources.MassFlowSource_T source2(
    redeclare package Medium = Medium,
    use_m_flow_in=true,
    m_flow=3,
    T=289.15,
    nPorts=1) "Fluid reservoir at cold side"
    annotation (Placement(transformation(extent={{-56,-48},{-36,-28}})));
  IBPSA.Fluid.Sources.Boundary_pT sink2(redeclare package Medium = Medium,
      nPorts=1) "Fluid reservoir at hot line" annotation (Placement(
        transformation(
        extent={{-10,-10},{10,10}},
        rotation=180,
        origin={72,-38})));
  Modelica.Blocks.Sources.Cosine cosine2(
    amplitude=2.5,
    freqHz=1/1e7,
    offset=1)
    annotation (Placement(transformation(extent={{-90,-40},{-70,-20}})));
  IBPSA.Fluid.Storage.Stratified tan(
    redeclare package Medium = Medium,
    m_flow_nominal=10,
    VTan=200,
    hTan=10,
    dIns=0.03,
    nSeg=5,
    T_start=285.15) "Storage tank for ectogrid"
    annotation (Placement(transformation(extent={{2,20},{22,40}})));
  IBPSA.Fluid.Sources.MassFlowSource_T source1(
    redeclare package Medium = Medium,
    use_m_flow_in=true,
    m_flow=3,
    T=289.15,
    nPorts=1) "Fluid reservoir at cold side"
    annotation (Placement(transformation(extent={{-54,20},{-34,40}})));
  IBPSA.Fluid.Sources.Boundary_pT sink1(redeclare package Medium = Medium,
      nPorts=1) "Fluid reservoir at hot line" annotation (Placement(
        transformation(
        extent={{-10,-10},{10,10}},
        rotation=180,
        origin={74,30})));
  Modelica.Blocks.Sources.Cosine cosine1(
    amplitude=2.5,
    freqHz=1/1e7,
    offset=1)
    annotation (Placement(transformation(extent={{-88,28},{-68,48}})));
equation 
  connect(sink2.ports[1], tan2.port_b)
    annotation (Line(points={{62,-38},{20,-38}}, color={0,127,255}));
  connect(cosine2.y, source2.m_flow_in)
    annotation (Line(points={{-69,-30},{-58,-30}}, color={0,0,127}));
  connect(source2.ports[1], tan2.port_a)
    annotation (Line(points={{-36,-38},{0,-38}}, color={0,127,255}));
  connect(sink1.ports[1], tan.port_b)
    annotation (Line(points={{64,30},{22,30}}, color={0,127,255}));
  connect(cosine1.y,source1. m_flow_in)
    annotation (Line(points={{-67,38},{-56,38}},   color={0,0,127}));
  connect(source1.ports[1], tan.port_a)
    annotation (Line(points={{-34,30},{2,30}}, color={0,127,255}));
  annotation (experiment(StopTime=41500000, Interval=3600),
    Icon(coordinateSystem(preserveAspectRatio=false)),
    Diagram(coordinateSystem(preserveAspectRatio=false)),
    uses(Modelica(version="3.2.2"), IBPSA(version="3.0.0")));
end StorageTestDouble;

```

The examples were simulated on Windows 10 Pro with Dymola 2019 and 2020, at both versions the issue still remains.

**Comment by Mathadon** [comment] 2019-06-11 17:06
Can you be more specific about what the problem is? To me those results are as expected.

**Comment by EnginUcar** [comment] 2019-06-12 07:21
Sure! I simulated the first example again with a start temperature ```T_start = 283.15```K. By means of the next figure we actually would expect these results:

![StorageTest](https://user-images.githubusercontent.com/51709365/59330500-f102a480-8cf1-11e9-9125-5709a1b61116.png)

The figure shows the prescribed cosine function of the massflow and the resulting temperatures inside the storage. For all other start temperatures except ```T_start = 284.15``` K we get the same consistent periodic behaviour while simulating the first example ```StorageTestSingle```. So i am a bit confused why the first issue i mentioned above only occurrs at ```T_start = 284.15``` K.

**Comment by Mathadon** [comment] 2019-06-12 19:50
Oh, now I get it. I did not realize that one of the four periods dropped out. I'm pretty sure that this is caused by the time integrator taking too large step sizes. The temperatures don't change a lot for quite a long time, causing the time integrator to take such a large step that it steps over the transient response of the sine. You should be able to avoid this behavior by using a different integrator, choosing a smaller tolerance, or by forcing a fixed time step e.g. using Euler integration.

**Comment by EnginUcar** [comment] 2019-06-13 07:39
Ok, thank you very much for your help. I am just a bit confused because the drop out of one period at both examples seemed so randomly to me. At ```StorageTestDouble``` there is no drop out at both tanks when setting for example ```T_start = 284.15```K for the first tank and ```T_start = 283.15```K for the second tank, but when i set ```T_start = 285.15```K for the first tank **both** tanks have a drop out of the period. 

By changing the tolerance and integration method both systems have been working fine.

**Comment by Mathadon** [comment] 2019-06-13 07:44
this issue can then be closed as far as I am concerned

**Closed by Mathadon** 2019-06-13 07:44 UTC
