### ISSUE TITLE
release 3.0

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#996] opened 2018-08-08 09:11 UTC
To follow up on https://github.com/ibpsa/project1/wiki/2018-06-14-library-development :

We have a project deliverable at the end of August by when we'd like to merge IBPSA (including the bore field model) into IDEAS 2.0. Can we compile a list of issues that have to be merged in 3.0? Also (@MassimoCimmino @damienpicard @mwetter ) is it feasible to merge the bore field model by then?

Thanks!

Todo:
 - [x] #974 borefield
 - [x] #999 remove function
 - [x] #997 
 - [x] #994

**Comment by MassimoCimmino** [comment] 2018-08-10 15:34
@Mathadon The bore field model is complete, pending some minor changes to the documentation and final adjustments to the parameters of the validation models that rely on experimental data. This will be complete by end of August. However, it will be best if @damienpicard can look through the models since his name is attached to them and I am told he is on vacations for all of August. The models still need review.

**Comment by damienpicard** [comment] 2018-08-14 19:30
@MassimoCimmino I'm back in town and I have made some minor comments on #974 
Thanks a lot for the work and tell me if you want me to do anything else for the release.
I can start working on the paper by October at the latest, but probably already in September.

**Comment by Mathadon** [comment] 2018-08-24 07:57
@mwetter can we make a release once #974 is merged? I presume we also want to merge #999 ? Any others?

**Comment by mlauster** [comment] 2018-08-24 09:50
I would like to have #997 also in this release. The issue is solved, I'm just running some larger examples to see the impact on the results in application use cases.

**Comment by mwetter** [comment] 2018-08-24 14:31
I suggest https://github.com/ibpsa/modelica-ibpsa/pull/994 should also be included as this is also backward incompatible. I have not yet had a chance to review it and understand what the implications are for having to specify an *average increment of weather data*. #994 also seems to require test cases that show that the problem is fixed. Could Aachen add such tests?

**Comment by mlauster** [comment] 2018-08-29 09:11
@mwetter, @AnaConstantin is on parental leave and might not find the time to implement these tests.

**Comment by mwetter** [comment] 2018-08-29 15:21
@mlauster Could you add these tests? I am fully booked this and early next week and tried to make the borehole model a priority

**Comment by AnaConstantin** [comment] 2018-08-29 21:16
Hello everyone, I have now become aware of this issue. I can try to do this by Monday, since there is a push to do this release it means that the process might go swiftly. So yes, I'll do the tests as soon as possible.

**Comment by mwetter** [comment] 2018-09-25 18:03
Now would be a good time to tag a release. I can do it this week. OK with @mlauster and @nytschgeusen

**Comment by mlauster** [comment] 2018-09-25 18:13
:+1:

**Comment by beutlich** [comment] 2018-09-25 18:41
Do you have any intention to also run a regression against MSL v3.2.3?

**Comment by mwetter** [comment] 2018-09-26 03:00
It should work with MSL 3.2.3. We did testing in https://github.com/ibpsa/modelica-ibpsa/issues/934
Maybe @Mathadon can do some tests of the current version as I am on travel.

**Comment by beutlich** [comment] 2018-09-26 06:44
Thanks for testing and letting me know.

**Comment by mwetter** [comment] 2018-09-27 19:53
This has now been merged to the master and release v3.0.0 has been tagged.

**Closed by mwetter** 2018-09-27 19:53 UTC

**Comment by Mathadon** [comment] 2018-09-28 06:33
IDEAS 2.0 has been released. Thanks all!
