### ISSUE TITLE
Fluid/Interfaces/Examples/Humidifier_u.mo fails in OpenModelica

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica-ibpsa#187] opened 2015-03-16 21:44 UTC
The model `Annex60.Fluid.Interfaces.Examples.Humidifier_u` fails in OpenModelica with the message:

```
Error: Variable T in package Annex60.Fluid.Interfaces.Examples.Humidifier_u.Humidifier$hea1 is not constant.
[/var/lib/hudson/jobs/OpenModelica_TEST_ALL_LIBRARIES/workspace/OpenModelica/build/lib/omlibrary/Annex60 0.1/Fluid/Interfaces/Examples/Humidifier_u.mo:113:45-113:58:writable] Error: Variable hea1.staB.T not found in scope Annex60.Fluid.Interfaces.Examples.Humidifier_u.
Error: Error occurred while flattening model Annex60.Fluid.Interfaces.Examples.Humidifier_u
```

The issue is that for the asserts, the variables `staA.T` and `staA.X[1]` (and the same for `B`) are accessed, but these are not always state variables, and OpenModelica therefore thinks they do not exist.

As a fix, `Annex60.Fluid.Interfaces.Examples.Humidifier_u.Humidifier` should be deleted, and sensors should be used as is done for `Annex60.Fluid.Interfaces.Examples.HeaterCooler_u`.

**Comment by thorade** [comment] 2017-10-19 12:46
The error message is now a different one:
https://libraries.openmodelica.org/branches/master/IBPSA_latest/files/IBPSA_latest_IBPSA.Fluid.Interfaces.Examples.Humidifier_u.err

Humidifier should propagate the Medium, I think:
```modelica
protected
  model Humidifier
    "Model for humidifier that adds a variable for the thermodynamic states at its ports"
    extends IBPSA.Fluid.Humidifiers.Humidifier_u(
      redeclare replaceable package Medium = Medium);
```
but with that version, OpenModelica has a StackOverflow.

Would that change be correct? And should I push it?

**Comment by thorade** [comment] 2017-10-19 13:02
After thinking about it some more, the redeclaration should not be necessary and is not done in other similar models.

Maybe that error is instead a duplicate of https://trac.openmodelica.org/OpenModelica/ticket/4235 ?

**Comment by mwetter** [comment] 2017-10-20 22:31
Redeclaration is indeed not necessairy.

**Comment by thorade** [comment] 2017-10-23 11:41
Closing for now, should be checked again once the new OMC frontend is available:
https://trac.openmodelica.org/OpenModelica/ticket/4138
https://trac.openmodelica.org/OpenModelica/milestone/2.0.0

**Closed by thorade** 2017-10-23 11:41 UTC
Labels: enhancement, wontfix
